name: "[<funxxfun>] CIワークフロー"

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - uses: actions/checkout@v4

      # [課題] Node.js v20の環境をセットアップする
      - name: Setup Node.js v20
        uses: actions/setup-node@v2
        with:
          node-version: 20


      # [課題] Nuxt.jsアプリケーションのパッケージをインストールする
      - name: Install dependencies
        run: npm ci
        working-directory: app

      # [課題] Nuxt.jsアプリケーションをビルドする
      - name: Build application
        run: npm run build
        working-directory: app

      # [課題] Nuxt.jsアプリケーションのテストを実行する
      - name: Test application
        run: npm run e2e
        working-directory: app
